"""agregar constraint unica a variantes

Revision ID: b50667dc21cd
Revises: 11438eefc602
Create Date: 2026-10-06 15:08:00.678790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50667dc21cd'
down_revision = '11438eefc602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variantes_producto', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_variante_producto_talla_color', ['producto_id', 'talla', 'color'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variantes_producto', schema=None) as batch_op:
        batch_op.drop_constraint('uq_variante_producto_talla_color', type_='unique')

    # ### end Alembic commands ###
