"""crear tabla disenos

Revision ID: b8d07486fc46
Revises: b50667dc21cd
Create Date: 2026-10-06 17:05:55.657339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d07486fc46'
down_revision = 'b50667dc21cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disenos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('public_id', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disenos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disenos_nombre'), ['nombre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disenos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disenos_nombre'))

    op.drop_table('disenos')
    # ### end Alembic commands ###
